.TH "_adafruit_i_o" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_adafruit_i_o \- Adafruit IO MQTT 
.PP
Gestion de la connexion au broker Adafruit IO et des données de télémétrie \&. Adafruit nous permet de recuperer les états de santé des utilisateurs et de les afficher sur une interface web\&.
.PP
\fBCTAdafruitIO\&.h\fP 
