.TH "_c_t_n_t_p" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_n_t_p \- NTP Contact Tracer 
.PP
CTNTP est un module qui permet de récupérer l'heure depuis un serveur NTP\&. Cette heure est utilisée pour l'horodatage des interactions avec d'autres appareils\&.
.PP
\fBCTNTP\&.h\fP 
