.TH "_c_t_events" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_events \- Événements de l'application Contact Tracer 
.PP
CTEvents est un module qui contient les callbacks des événements de l'application\&. Il est possible d'ajouter des callbacks pour les événements suivants :
.PP
.IP "\(bu" 2
Changement des identifiants de l'appareil (\fBonDeviceCredentialsChangedCallbacks\fP)
.IP "\(bu" 2
Changement des identifiants du réseau (\fBonNetworkCredentialsChangedCallbacks\fP)
.IP "\(bu" 2
Changement de la configuration de surveillance (\fBonMonitoringConfigChangedCallbacks\fP)
.IP "\(bu" 2
Changement de l'état de santé (\fBonHealthStatusChangedCallbacks\fP)
.PP
.PP
\fBCTEvents\&.h\fP 
