.TH "_c_t_wi_f_i" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_wi_f_i \- WiFi Contact Tracer 
.PP
CTWiFI est un module qui contient la logique de connexion au réseau WiFi\&. Il permet de créer un point d'accès WiFi pour permettre à l'utilisateur de configurer l'appareil, (\fBPortail Captif Contact Tracer\fP) Ainsi que de se connecter à un réseau WiFi pour envoyer les données de télémétrie\&.
.PP
\fBCTWiFI\&.h\fP 
