.TH "_c_t_s_p_i_f_f_s" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_s_p_i_f_f_s \- SPIFFS Contact Tracer 
.PP
CTSPIFFS est un module qui permet de d'intéragir avec la mémoire flash SPIFFS du système\&. Il permet de lire et d'écrire des fichiers JSON\&. Ce module contient des fonctions utilitaires de lecture et d'écriture de fichiers JSON simples à utiliser\&. En utilisant ce module, il est possible de modifier les différentes variables globales système :
.PP
.IP "\(bu" 2
\fBdevice_name\fP : Le nom de l'appareil
.IP "\(bu" 2
\fBdevice_password\fP : Le mot de passe de l'appareil
.IP "\(bu" 2
\fBnet_ssid\fP : Le nom du réseau WiFi
.IP "\(bu" 2
\fBnet_password\fP : Le mot de passe du réseau WiFi
.IP "\(bu" 2
\fBmonitoring_time\fP : Le temps de surveillance
.IP "\(bu" 2
\fBmonitoring_distance\fP : La distance de surveillance
.IP "\(bu" 2
\fBuser_status\fP : L'état de santé de l'utilisateur
.IP "\(bu" 2
\fBtemperature_threshold\fP : Le seuil de température
.PP
.PP
\fBCTSPIFFS\&.h\fP 
