.TH "_c_t_monitoring" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_monitoring \- Contact Tracer Surveillance 
.PP
Surveillance des Utilisateurs Contact Tracer (CT) à proximité\&. Lorsque deux utilisateurs CT sont à proximité, ils échangent leurs adresses BT et se surveillent mutuellement\&. Si l'un des deux utilisateurs est malade (\fBuser_status\fP), et que le temps d'intéraction dépasse le seuil de contact (\fBmonitoring_time\fP) l'autre est notifié et devient un cas contact\&.
.PP
\fBCTMonitoring\&.h\fP 
