.TH "_c_t_web_server" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_web_server \- Portail Captif Contact Tracer 
.PP
CTWebServer est un module qui contient la configuration du serveur web de l'application; son implémentation ainsi que le système de Portail Captif\&. Le Portail Captif permet de configurer l'appareil en se connectant à son point d'accès réseau\&.
.PP
\fBCTWebServer\&.h\fP 
