.TH "_c_t_debug" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_debug \- Debug Contact Tracer 
.PP
CTDebug est un module qui permet d'activer ou de désactiver les messages de debug\&. Lorsque MYDEBUG est défini, les messages de debug sont affichés sur le port série\&.
.PP
\fBCTDebug\&.h\fP 
