.TH "_c_t_l_e_d" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_l_e_d \- LED d'indications Contact Tracer 
.PP
CTLED est un module qui sert à gérer la LED de l'appareil\&. Lorsque l'Utilisateur est en bonne santé, la LED est allumée en permanence\&. Lorsque l'Utilisateur est en contact avec une personne malade, la LED fluctue en luminosité de façon sinusoidale\&. Lorsque l'Utilisateur est malade, la LED clignote\&.
.PP
\fBCTLED\&.h\fP 
