.TH "_c_t_d_h_t" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_t_d_h_t \- DHT11 Contact Tracer 
.PP
CTDHT est un module qui permet de récupérer les données du capteur DHT11\&. Lorsque la température excède le seuil de température (\fBtemperature_threshold\fP), l'appareil est marqué comme malade\&.
.PP
\fBCTDHT\&.h\fP 
