.TH "CTDebug.h" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTDebug.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMYDEBUG_PRINT\fP(x)"
.br
.ti -1c
.RI "#define \fBMYDEBUG_PRINTDEC\fP(x)"
.br
.ti -1c
.RI "#define \fBMYDEBUG_PRINTHEX\fP(x)"
.br
.ti -1c
.RI "#define \fBMYDEBUG_PRINTLN\fP(x)"
.br
.ti -1c
.RI "#define \fBMYDEBUG_PRINTF\fP(x)"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBsetupDebug\fP ()"
.br
.RI "Fonction qui permet d'initialiser le port série pour le debug\&. "
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define MYDEBUG_PRINT(x)"

.PP
Définition à la ligne \fB17\fP du fichier \fBCTDebug\&.h\fP\&.
.SS "#define MYDEBUG_PRINTDEC(x)"

.PP
Définition à la ligne \fB18\fP du fichier \fBCTDebug\&.h\fP\&.
.SS "#define MYDEBUG_PRINTF(x)"

.PP
Définition à la ligne \fB21\fP du fichier \fBCTDebug\&.h\fP\&.
.SS "#define MYDEBUG_PRINTHEX(x)"

.PP
Définition à la ligne \fB19\fP du fichier \fBCTDebug\&.h\fP\&.
.SS "#define MYDEBUG_PRINTLN(x)"

.PP
Définition à la ligne \fB20\fP du fichier \fBCTDebug\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void setupDebug ()"

.PP
Fonction qui permet d'initialiser le port série pour le debug\&. 
.PP
Définition à la ligne \fB27\fP du fichier \fBCTDebug\&.h\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Trio d'Hommes Forts à partir du code source\&.
