.TH "CTDHT.h" 3 "Lundi 5 Juin 2023" "Trio d'Hommes Forts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTDHT.h
.SH SYNOPSIS
.br
.PP
\fC#include <esp32DHT\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDHT_PIN\fP   33"
.br
.ti -1c
.RI "#define \fBDHT_TYPE\fP   DHT11"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBsetupDhtSensor\fP ()"
.br
.RI "Initialise le capteur DHT11\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "DHT11 \fBCTDHT\fP"
.br
.ti -1c
.RI "uint32_t \fBdelayMS\fP = 5000"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define DHT_PIN   33"

.PP
Définition à la ligne \fB12\fP du fichier \fBCTDHT\&.h\fP\&.
.SS "#define DHT_TYPE   DHT11"

.PP
Définition à la ligne \fB13\fP du fichier \fBCTDHT\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void setupDhtSensor ()"

.PP
Initialise le capteur DHT11\&. 
.PP
Définition à la ligne \fB22\fP du fichier \fBCTDHT\&.h\fP\&.
.SH "Documentation des variables"
.PP 
.SS "DHT11 CTDHT"

.PP
Définition à la ligne \fB15\fP du fichier \fBCTDHT\&.h\fP\&.
.SS "uint32_t delayMS = 5000"

.PP
Définition à la ligne \fB16\fP du fichier \fBCTDHT\&.h\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Trio d'Hommes Forts à partir du code source\&.
